#ifndef SVISTOK_CHARACTERIZATION_ASTERISK_MODULE_H
#define SVISTOK_CHARACTERIZATION_ASTERISK_MODULE_H
#define AST_MODULE_LOAD_SUCCESS 0
#define AST_MODULE_LOAD_DECLINE -1
#define AST_MODULE_LOAD_FAILURE -2
#define AST_MODULE "chan_svistok"
#define MODULE_VERSION "legacy"
#define PACKAGE_REVISION "oracle"
#define MODULE_URL "local"
#define MODULE_BUGREPORT "local"
#endif
